highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Arunav Shandilya
email: arunavshandilya96@gmail.com
description: Website of Arunav Shandilya
keywords: arunav, shandilya, iiit, bhubaneswar,developer, geek, programmer,github
baseurl: ""
url: https://shandilya21.github.io
name: Arunav SHandilya\'s blog
author:
  name: Arunav Shandilya
  email: arunavshandilya96@gmail.com
